### ISSUE TITLE
Some issue happened

### ISSUE THREAD

**Issue by CJEQ** [bermanmaxim/superpixPool#6]
I setup the lib by "python setup.py install" and then run "python test_GPUpool.py". And I got an error:
INPUT` ARRAY  -----------------
 tensor([[[[ 3.7814e-01,  7.9083e-01,  1.1148e+00,  ..., -5.6905e-01,
           -6.1719e-01,  1.1416e+00],
          [-1.2854e+00, -5.0356e-01,  1.0880e+00,  ..., -2.5250e-02,
           -4.5123e-01, -5.6882e-01],
          [ 5.8038e-01,  4.1362e-01, -2.8838e-01,  ..., -7.5795e-01,
           -1.3728e+00,  1.6197e+00],
          [-9.6522e-01,  1.3335e+00,  4.2776e-01,  ..., -1.8920e+00,
            5.8105e-01, -1.4075e+00],
          [ 1.4723e+00,  4.3477e-01,  1.2817e+00,  ...,  6.4713e-01,
            1.0534e-01,  1.0570e+00],
          [ 1.6522e+00,  6.2514e-01,  1.6110e+00,  ...,  2.5364e-01,
           -1.7211e+00,  6.2385e-01]],
         [[ 7.9823e-01,  1.4645e+00, -1.0436e+00,  ...,  1.4989e-01,
            1.1836e+00,  2.7629e-01],
          [ 9.3548e-01, -5.5506e-01, -2.6804e-01,  ...,  3.0556e-01,
           -2.2063e-01,  5.5239e-01],
          [-1.4710e+00,  1.7432e-01,  3.2908e-01,  ...,  4.7178e-01,
            9.2178e-01,  1.1642e+00],
          [ 4.6409e-01, -5.4032e-01, -8.8076e-01,  ..., -1.4097e+00,
           -7.8303e-01,  2.0206e+00],
          [ 2.7877e-01, -3.4751e-01,  5.0900e-01,  ..., -5.9144e-01,
            5.2281e-01, -5.5037e-01],
          [-8.1993e-02, -5.1163e-01, -3.9549e-01,  ...,  1.9985e+00,
            7.0099e-02, -3.8762e-02]],
         [[-1.3490e+00,  1.9204e+00,  4.6448e-01,  ...,  7.6993e-01,
           -1.9323e+00,  5.6556e-01],
          [-4.9886e-01, -1.5755e+00, -1.0379e+00,  ..., -1.1948e-01,
            8.4629e-01,  1.2183e+00],
          [-1.3623e+00, -2.3714e-01,  6.9222e-01,  ..., -8.7767e-02,
            2.5579e-01, -8.8254e-01],
          [-1.2533e-01, -6.9848e-01, -7.9745e-01,  ...,  2.1127e-01,
            1.0833e+00,  5.1565e-01],
          [ 1.1365e-01,  8.5013e-01,  4.4658e-01,  ...,  7.1052e-01,
            8.6058e-01,  5.0149e-01],
          [-1.0084e+00,  1.2770e+00,  9.5154e-01,  ...,  1.2924e+00,
            3.0311e-01,  9.9258e-01]],..
         [[-1.2106e+00, -1.1577e+00,  2.1545e+00,  ..., -6.6592e-01,
           -3.5569e-01, -1.4535e+00],
          [ 3.1645e-01, -1.1822e+00, -2.1051e-01,  ...,  1.1106e+00,
            1.4587e-01,  1.3257e+00],
          [-2.3012e+00,  2.0952e+00, -1.2745e+00,  ...,  7.1895e-01,
           -4.4505e-01, -1.5681e+00],
          [-9.1122e-01,  7.9414e-01, -7.8844e-01,  ..., -8.2005e-01,
           -5.3249e-01, -1.5845e+00],
          [-8.0232e-01,  7.4821e-01,  2.1659e-01,  ..., -3.6049e-01,
           -6.8920e-01, -3.0863e+00],
          [ 9.6989e-01, -6.1435e-01,  1.9915e+00,  ..., -1.1210e+00,
            6.0345e-01, -4.3096e-01]],
         [[-6.6086e-01, -6.1419e-01,  1.0672e+00,  ...,  9.4679e-01,
            1.7144e-01,  7.5758e-01],
          [ 3.7551e-01,  5.9042e-01, -9.0842e-01,  ...,  3.9907e-01,
            7.7149e-01,  1.0758e+00],
          [-4.0228e-01, -7.5170e-01, -9.3077e-01,  ..., -9.6583e-01,
            1.3838e+00,  8.4441e-01],
          [-1.0051e+00,  6.9216e-01,  6.3819e-01,  ...,  1.2028e-02,
            2.4493e-01, -1.0220e+00],
          [-1.7311e-01, -3.5993e-01, -1.4137e+00,  ..., -6.4306e-02,
            1.3659e+00,  2.8960e-01],
          [-5.8856e-01,  9.4296e-01,  5.1638e-01,  ...,  9.6898e-01,
           -1.1527e+00,  1.9936e+00]],
         [[-9.6107e-01, -8.0406e-01, -3.2530e-01,  ...,  1.4787e+00,
            9.5833e-02,  5.4245e-02],
          [ 3.9939e-01, -1.8442e-01,  7.5645e-03,  ...,  5.0981e-01,
            9.4536e-01,  1.4599e+00],
          [ 3.0651e-02,  1.8993e+00,  1.4950e-01,  ...,  1.2373e+00,
           -9.2724e-01, -3.6400e-01],
          [ 2.5349e-01, -3.7167e-01,  7.7780e-01,  ..., -1.0251e+00,
            1.5099e+00,  1.6357e+00],
          [ 1.9537e-01,  7.3182e-01, -7.5995e-01,  ..., -2.2166e-01,
            1.3942e+00, -1.8264e-01],
          [-5.4935e-01,  3.8237e-01,  2.4256e+00,  ..., -1.9933e+00,
           -8.8826e-01, -1.5598e+00]]]], device='cuda:0')
Segmentation fault (core `dumped).
I use ubuntu 14.04, NVIDIA K40, gcc 5. After debug the code, I found this error happend in runing `out = spx_gpu.forward(img, spx, K)` in suppixpool_layer.py. How should I fix this error?

**Comment by bermanmaxim** [comment]
Hello, sorry, I don't think we have run into this issue, and we don't plan to invest a lot of time of maintaining this work/setting it up to date. It could be related to the pytorch version. @Mathijssch do you have an idea?

**Comment by Mathijssch** [comment]
Indeed, I assume it has to do with incompatibility with newer Pytorch versions, since this test scripts did not result in any issues previously. The only thing I can immediately think of right now, is perhaps some type mix-up: e.g., doubles which are interpreted as floats, causing out of range memory accesses in the CUDA kernel, but that's just a guess.

**Comment by bermanmaxim** [comment]
`wontfix` as we do not want to invest time in this project right now, PR welcome however! Thanks for your understanding.
