### ISSUE TITLE
suppixpool_cuda.cpp:38:44: error: could not convert ‘torch::CUDA((c10::ScalarType)3)’ from ‘at::TypeExtendedInterface’ to ‘c10::IntList {aka c10::ArrayRef<long int>}’

### ISSUE THREAD

**Issue by fbi0817** [bermanmaxim/superpixPool#7]
Hello, Thanks for sharing your code. I have a problem when running:
  python_ setup.py install

The error shows:

suppixpool_cuda.cpp:38:44: error: could not convert ‘torch::CUDA((c10::ScalarType)3)’ from ‘at::TypeExtendedInterface’ to ‘c10::IntList {aka c10::ArrayRef<long int>}’
   at::Tensor output = at::zeros(torch::CUDA(at::kInt), {batch_size,
                                            ^
suppixpool_cuda.cpp:41:73: error: could not convert ‘c10::kInt’ from ‘const c10::ScalarType’ to ‘c10::IntList {aka c10::ArrayRef<long int>}’
 ensor outIdx = -at::ones(at::kInt, {batch_size, channels_size, K});
                                                                  ^
error: command 'gcc' failed with exit status 1

I have upgraded my Pytorch from 0.4.0 to 1.0.0 and my gcc version is "gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609". But the error still appears. I am wondering what is your settings?

**Comment by Idiom1999** [comment]
I run python setup.py install, but appear the error:
RuntimeError: Error compiling objects for extension.
What wrong?
